// Uma academia tem alunos,
// personal trainers
// e planos de treino. 
// Um aluno contrata um personal.
// O personal monta fichas de treino para o aluno. 
// Cada ficha tem vários exercícios,
// e cada exercício em uma ficha tem séries,
// repetições e carga definidas.
// Um exercício pode aparecer em várias fichas diferentes.

CREATE TABLE "alunos" (
  "id_aluno" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nome" varchar(80) NOT NULL,
  "cpf_aluno" char(11) NOT NULL,
  "dt_nasc" date NOT NULL,
  "sexo" char NOT NULL,
  "dt_inscricao" date NOT NULL
);

CREATE TABLE "personal" (
  "id_personal" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nome" varchar(80) NOT NULL,
  "cpf_personal" char(11) NOT NULL,
  "dt_nasc" date NOT NULL,
  "sexo" char NOT NULL,
  "dt_admissao" date NOT NULL,
  "dt_demissao" date
);

CREATE TABLE "vinculo_aluno_personal" (
  "id_vinculo" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_aluno" integer NOT NULL,
  "id_personal" integer NOT NULL,
  "id_contrato" integer NOT NULL
);

CREATE TABLE "contrato" (
  "id_contrato" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "ativo" boolean NOT NULL,
  "dta_inicio" date NOT NULL,
  "dta_fim" date,
  "valor_mensal" decimal(10,2) NOT NULL
);

CREATE TABLE "exercicios" (
  "id_exercicio" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nome_exercicio" text NOT NULL
);

CREATE TABLE "ficha" (
  "id_ficha" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_vinculo" integer NOT NULL
);

CREATE TABLE "planejamento" (
  "id_plano" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_ficha" integer NOT NULL,
  "id_exercicio" integer NOT NULL,
  "serie" integer NOT NULL,
  "repeticoes" integer NOT NULL
);

ALTER TABLE "vinculo_aluno_personal" ADD FOREIGN KEY ("id_personal") REFERENCES "personal" ("id_personal") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vinculo_aluno_personal" ADD FOREIGN KEY ("id_aluno") REFERENCES "alunos" ("id_aluno") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contrato" ADD FOREIGN KEY ("id_contrato") REFERENCES "vinculo_aluno_personal" ("id_contrato") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "planejamento" ADD FOREIGN KEY ("id_exercicio") REFERENCES "exercicios" ("id_exercicio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "planejamento" ADD FOREIGN KEY ("id_ficha") REFERENCES "ficha" ("id_ficha") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ficha" ADD FOREIGN KEY ("id_vinculo") REFERENCES "vinculo_aluno_personal" ("id_vinculo") DEFERRABLE INITIALLY IMMEDIATE;


  
//////////////////////////
table alunos{
  id_aluno integer [pk, increment,not null]
  nome varchar (80) [not null]
  cpf_aluno char(11)  [not null]
  dt_nasc date [not null]
  sexo char [not null]
  dt_inscricao date [not null]
}

table personal{
  id_personal integer [pk, increment,not null]
  nome varchar (80) [not null]
  cpf_personal char(11)  [not null]
  dt_nasc date [not null]
  sexo char [not null]
  dt_admissao date [not null]
  dt_demissao date
}

table vinculo_aluno_personal{
  id_vinculo integer [pk, increment,not null]
  id_aluno integer [not null]
  id_personal integer [not null]
  id_contrato integer [not null]
}
table contrato{
  id_contrato integer [pk,increment, not null]
  ativo boolean [not null]
  dta_inicio date [not null]
  dta_fim date
  valor_mensal decimal (10,2) [not null]
}
table exercicios{
  id_exercicio integer [pk, increment,not null]
  nome_exercicio text [not null]
}

table ficha{
  id_ficha integer [pk, increment,not null]
  id_vinculo integer [not null]
  

}
table planejamento{
  id_plano integer [pk,increment,not null]
  id_ficha integer [not null]
  id_exercicio integer [not null]
  serie integer [not null]
  repeticoes integer [not null]
}



Ref: "personal"."id_personal" < "vinculo_aluno_personal"."id_personal"

Ref: "alunos"."id_aluno" < "vinculo_aluno_personal"."id_aluno"

Ref: "vinculo_aluno_personal"."id_contrato" - "contrato"."id_contrato"

Ref: "exercicios"."id_exercicio" < "planejamento"."id_exercicio"

Ref: "ficha"."id_ficha" < "planejamento"."id_ficha"

Ref: "vinculo_aluno_personal"."id_vinculo" < "ficha"."id_vinculo"
