CREATE TABLE "medicos" (
  "id_medico" int PRIMARY KEY NOT NULL,
  "nome_medico" varchar(100) NOT NULL,
  "id_especialidade" varchar(50) NOT NULL
);

CREATE TABLE "especialidade" (
  "id_especialidade" int PRIMARY KEY NOT NULL,
  "funcao" varchar(100) NOT NULL,
  "cod_crm" varchar(50) NOT NULL
);

CREATE TABLE "paciente" (
  "id_paciente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "cpf" varchar(11) NOT NULL,
  "nome" varchar(100) NOT NULL,
  "dt_nascimento" timestamp NOT NULL,
  "cep" char(8) NOT NULL
);

CREATE TABLE "consulta" (
  "id_consulta" int PRIMARY KEY NOT NULL,
  "dt_consulta" timestamp NOT NULL,
  "id_medico" int NOT NULL,
  "id_paciente" int NOT NULL
);

CREATE TABLE "receita" (
  "id_receita" int PRIMARY KEY NOT NULL,
  "id_consulta" int NOT NULL
);

CREATE TABLE "remedios" (
  "id_desc_remedio" int PRIMARY KEY NOT NULL,
  "nome_remedio" varchar(100) NOT NULL,
  "fabricante" varchar(100) NOT NULL
);

CREATE TABLE "remedios_preescritos_receita" (
  "id_pedido" int PRIMARY KEY NOT NULL,
  "dose" float NOT NULL,
  "instrucoes" text NOT NULL,
  "id_receita" int NOT NULL,
  "id_desc_remedio" int NOT NULL
);

ALTER TABLE "consulta" ADD FOREIGN KEY ("id_paciente") REFERENCES "paciente" ("id_paciente") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "consulta" ADD FOREIGN KEY ("id_medico") REFERENCES "medicos" ("id_medico") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "especialidade" ADD FOREIGN KEY ("id_especialidade") REFERENCES "medicos" ("id_especialidade") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "receita" ADD FOREIGN KEY ("id_consulta") REFERENCES "consulta" ("id_consulta") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "remedios_preescritos_receita" ADD FOREIGN KEY ("id_receita") REFERENCES "receita" ("id_receita") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "remedios_preescritos_receita" ADD FOREIGN KEY ("id_desc_remedio") REFERENCES "remedios" ("id_desc_remedio") DEFERRABLE INITIALLY IMMEDIATE;
