CREATE TABLE "medicos" (
  "id_medico" int PRIMARY KEY NOT NULL,
  "nome_medico" varchar(100) NOT NULL,
  "id_especialidade" varchar(50) NOT NULL
);

CREATE TABLE "especialidade" (
  "id_especialidade" int PRIMARY KEY NOT NULL,
  "funcao" varchar(100) NOT NULL,
  "cod_crm" varchar(50) NOT NULL
);

CREATE TABLE "paciente" (
  "id_paciente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "cpf" varchar(11) NOT NULL,
  "nome" varchar(100) NOT NULL,
  "dt_nascimento" timestamp NOT NULL,
  "cep" char(8) NOT NULL
);

CREATE TABLE "consulta" (
  "id_consulta" int PRIMARY KEY NOT NULL,
  "dt_consulta" timestamp NOT NULL,
  "id_medico" int NOT NULL,
  "id_paciente" int NOT NULL
);

CREATE TABLE "receita" (
  "id_receita" int PRIMARY KEY NOT NULL,
  "id_consulta" int NOT NULL
);

CREATE TABLE "remedios" (
  "id_desc_remedio" int PRIMARY KEY NOT NULL,
  "nome_remedio" varchar(100) NOT NULL,
  "fabricante" varchar(100) NOT NULL
);

CREATE TABLE "remedios_preescritos_receita" (
  "id_pedido" int PRIMARY KEY NOT NULL,
  "dose" float NOT NULL,
  "instrucoes" text NOT NULL,
  "id_receita" int NOT NULL,
  "id_desc_remedio" int NOT NULL
);

ALTER TABLE "consulta" ADD FOREIGN KEY ("id_paciente") REFERENCES "paciente" ("id_paciente") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "consulta" ADD FOREIGN KEY ("id_medico") REFERENCES "medicos" ("id_medico") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "especialidade" ADD FOREIGN KEY ("id_especialidade") REFERENCES "medicos" ("id_especialidade") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "receita" ADD FOREIGN KEY ("id_consulta") REFERENCES "consulta" ("id_consulta") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "remedios_preescritos_receita" ADD FOREIGN KEY ("id_receita") REFERENCES "receita" ("id_receita") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "remedios_preescritos_receita" ADD FOREIGN KEY ("id_desc_remedio") REFERENCES "remedios" ("id_desc_remedio") DEFERRABLE INITIALLY IMMEDIATE;

--------------------


Table "medicos" {
  "id_medico" int [pk, not null]
  "nome_medico" varchar(100) [not null]
  "id_especialidade" varchar(50) [not null]
}

Table "especialidade" {
  "id_especialidade" int [pk, not null]
  "funcao" varchar(100) [not null]
  "cod_crm" varchar(50) [not null]
}

Table "paciente" {
  "id_paciente" INT [pk, not null, increment]
  "cpf" varchar(11) [not null]
  "nome" varchar(100) [not null]
  "dt_nascimento" timestamp [not null]
  "cep" char(8) [not null]
}

Table "consulta" {
  "id_consulta" int [pk, not null]
  "dt_consulta" timestamp [not null]
  "id_medico" int [not null]
  "id_paciente" int [not null]
}

Table "receita" {
  "id_receita" int [pk, not null]
  "id_consulta" int [not null]
}

Table "remedios" {
  "id_desc_remedio" int [pk, not null]
  "nome_remedio" varchar(100) [not null]
  "fabricante" varchar(100) [not null]
}

Table "remedios_preescritos_receita" {
  "id_pedido" int [pk, not null]
  "dose" float [not null]
  "instrucoes" text [not null]
  "id_receita" int [not null]
  "id_desc_remedio" int [not null]
}

Ref:"paciente"."id_paciente" < "consulta"."id_paciente"

Ref:"medicos"."id_medico" < "consulta"."id_medico"

Ref:"medicos"."id_especialidade" < "especialidade"."id_especialidade"

Ref:"consulta"."id_consulta" < "receita"."id_consulta"

Ref:"receita"."id_receita" < "remedios_preescritos_receita"."id_receita"

Ref:"remedios"."id_desc_remedio" < "remedios_preescritos_receita"."id_desc_remedio"

