'// Uma loja virtual vende produtos de vários vendedores. 
// Cada produto pertence a uma categoria que pode ter subcategorias. 
// Clientes fazem pedidos com vários produtos.
// Cada produto em um pedido tem quantidade e preço no momento da compra. 
// Um cliente pode avaliar um produto com nota e comentário após a compra.'

CREATE TABLE "vendedores" (
  "id_vendedor" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nome" varchar(30) NOT NULL
);

CREATE TABLE "fornecedor_produto" (
  "id_fornecedor" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_vendedor" integer NOT NULL,
  "id_produto" integer NOT NULL
);

CREATE TABLE "produtos" (
  "id_produto" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nome" varchar(20) NOT NULL,
  "id_categoria" varchar(50) NOT NULL
);

CREATE TABLE "categoria" (
  "id_cat_pai" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nome_categoria" varchar(50) NOT NULL,
  "id_cat_filha" integer NOT NULL
);

CREATE TABLE "pedidos" (
  "id_pedido" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_prod" integer NOT NULL,
  "id_cliente" integer NOT NULL
);

CREATE TABLE "valor_pedido" (
  "id_pedido" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "quantidade_prod" integer NOT NULL,
  "preco" float NOT NULL
);

CREATE TABLE "clientes" (
  "id_cliente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nome" varchar(30) NOT NULL
);

CREATE TABLE "avaliacoes" (
  "id_avaliacao" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_pedido" integer NOT NULL,
  "id_produto" integer NOT NULL,
  "id_cliente" integer NOT NULL,
  "nota_do_produto" float,
  "comentário" text
);

ALTER TABLE "fornecedor_produto" ADD FOREIGN KEY ("id_vendedor") REFERENCES "vendedores" ("id_vendedor") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fornecedor_produto" ADD FOREIGN KEY ("id_produto") REFERENCES "produtos" ("id_produto") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "produtos" ADD FOREIGN KEY ("id_categoria") REFERENCES "categoria" ("id_cat_pai") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedidos" ADD FOREIGN KEY ("id_cliente") REFERENCES "clientes" ("id_cliente") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedidos" ADD FOREIGN KEY ("id_prod") REFERENCES "produtos" ("id_produto") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "categoria" ADD FOREIGN KEY ("id_cat_filha") REFERENCES "categoria" ("id_cat_pai") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "valor_pedido" ADD FOREIGN KEY ("id_pedido") REFERENCES "pedidos" ("id_pedido") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "avaliacoes" ADD FOREIGN KEY ("id_produto") REFERENCES "pedidos" ("id_prod") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "avaliacoes" ADD FOREIGN KEY ("id_cliente") REFERENCES "pedidos" ("id_cliente") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "avaliacoes" ADD FOREIGN KEY ("id_pedido") REFERENCES "pedidos" ("id_pedido") DEFERRABLE INITIALLY IMMEDIATE;

------------------------

table vendedores {
  id_vendedor integer [pk, not null, increment]
  nome varchar(30) [not null]
}
table fornecedor_produto{
  id_fornecedor integer [pk, not null, increment]
  id_vendedor integer [not null]
  id_produto integer [not null]
}
table produtos {
  id_produto  integer [pk,not null, increment]
  nome varchar(20) [not null]
  id_categoria varchar (50) [not null]
}
Table categoria { 
  id_cat_pai integer [pk,increment,not null]
  nome_categoria varchar(50) [not null]
  id_cat_filha integer [not null]
}
table pedidos{
  id_pedido integer [pk, increment,not null]
  id_prod integer [not null]
  id_cliente integer [not null] 
}

table valor_pedido{
  id_pedido integer [increment,not null]
  quantidade_prod integer [not null]
  preco float [not null]  
}

table clientes{
  id_cliente integer [not null, pk, increment]
  nome varchar(30) [not null]
}
table avaliacoes{
  id_avaliacao integer [not null,pk,increment]
  id_pedido integer [not null]
  id_produto integer [not null]
  id_cliente integer [not null]
  nota_do_produto float
  comentário text 
}

Ref: "vendedores"."id_vendedor" < "fornecedor_produto"."id_vendedor"

Ref: "produtos"."id_produto" < "fornecedor_produto"."id_produto"

Ref: "categoria"."id_cat_pai" < "produtos"."id_categoria"

Ref: "clientes"."id_cliente" < "pedidos"."id_cliente"

Ref: "produtos"."id_produto" < "pedidos"."id_prod"

Ref: "categoria"."id_cat_pai" < "categoria"."id_cat_filha"

Ref: "pedidos"."id_pedido" - "valor_pedido"."id_pedido"



Ref: "pedidos"."id_prod" < "avaliacoes"."id_produto"

Ref: "pedidos"."id_cliente" < "avaliacoes"."id_cliente"

Ref: "pedidos"."id_pedido" < "avaliacoes"."id_pedido"
