'// Uma loja virtual vende produtos de vários vendedores. 
// Cada produto pertence a uma categoria que pode ter subcategorias. 
// Clientes fazem pedidos com vários produtos.
// Cada produto em um pedido tem quantidade e preço no momento da compra. 
// Um cliente pode avaliar um produto com nota e comentário após a compra.'

CREATE TABLE "vendedores" (
  "id_vendedor" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nome" varchar(30) NOT NULL
);

CREATE TABLE "vendedor_do_produto" (
  "id_vendedor_do_produto" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_vendedor" integer NOT NULL,
  "id_produto" integer NOT NULL
);

CREATE TABLE "produtos" (
  "id_produto" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nome" varchar(20) NOT NULL,
  "id_categoria" integer NOT NULL
);

CREATE TABLE "categoria" (
  "id_categoria" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nome" varchar(50) NOT NULL,
  "id_categoria_pai" integer
);

CREATE TABLE "pedidos" (
  "id_pedido" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_cliente" integer NOT NULL,
  "dt_pedido" date NOT NULL
);

CREATE TABLE "item_pedido" (
  "id_item" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_pedido" integer NOT NULL,
  "id_produto" integer NOT NULL,
  "quantidade" integer NOT NULL,
  "preco_momento" decimal(10,2) NOT NULL
);

CREATE TABLE "clientes" (
  "id_cliente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nome" varchar(30) NOT NULL
);

CREATE TABLE "avaliacao" (
  "id_avaliacao" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_cliente" integer NOT NULL,
  "id_produto" integer NOT NULL,
  "id_pedido" integer NOT NULL,
  "nota" decimal(3,1) NOT NULL,
  "comentario" text
);

ALTER TABLE "categoria" ADD FOREIGN KEY ("id_categoria_pai") REFERENCES "categoria" ("id_categoria") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "produtos" ADD FOREIGN KEY ("id_categoria") REFERENCES "categoria" ("id_categoria") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vendedor_do_produto" ADD FOREIGN KEY ("id_vendedor") REFERENCES "vendedores" ("id_vendedor") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vendedor_do_produto" ADD FOREIGN KEY ("id_produto") REFERENCES "produtos" ("id_produto") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedidos" ADD FOREIGN KEY ("id_cliente") REFERENCES "clientes" ("id_cliente") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "item_pedido" ADD FOREIGN KEY ("id_pedido") REFERENCES "pedidos" ("id_pedido") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "item_pedido" ADD FOREIGN KEY ("id_produto") REFERENCES "produtos" ("id_produto") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "avaliacao" ADD FOREIGN KEY ("id_cliente") REFERENCES "clientes" ("id_cliente") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "avaliacao" ADD FOREIGN KEY ("id_produto") REFERENCES "produtos" ("id_produto") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "avaliacao" ADD FOREIGN KEY ("id_pedido") REFERENCES "pedidos" ("id_pedido") DEFERRABLE INITIALLY IMMEDIATE;


------------------------

// Uma loja virtual vende produtos de vários vendedores. 
// Cada produto pertence a uma categoria que pode ter subcategorias. 
// Clientes fazem pedidos com vários produtos.
// Cada produto em um pedido tem quantidade e preço no momento da compra. 
// Um cliente pode avaliar um produto com nota e comentário após a compra.

table vendedores {
  id_vendedor integer [pk, not null, increment]
  nome varchar(30) [not null]
}
table vendedor_do_produto{
  id_vendedor_do_produto integer [pk, not null, increment]
  id_vendedor integer [not null]
  id_produto integer [not null]
}
table produtos {
  id_produto  integer [pk,not null, increment]
  nome varchar(20) [not null]
  id_categoria integer [not null]
}
Table categoria { 
  id_categoria integer [pk, increment, not null]
  nome varchar(50) [not null]
  id_categoria_pai integer // null = categoria raiz
}
table pedidos{
  id_pedido integer [pk, increment,not null]
  id_cliente integer [not null] 
  dt_pedido date [not null]
}

Table item_pedido {
  id_item integer [pk, increment, not null]
  id_pedido integer [not null]
  id_produto integer [not null]
  quantidade integer [not null]
  preco_momento decimal(10,2) [not null]
}
table clientes{
  id_cliente integer [not null, pk, increment]
  nome varchar(30) [not null]
}
Table avaliacao {
  id_avaliacao integer [pk, increment, not null]
  id_cliente integer [not null]
  id_produto integer [not null]
  id_pedido integer [not null]
  nota decimal(3,1) [not null]
  comentario text
}

Ref: categoria.id_categoria_pai > categoria.id_categoria
Ref: produtos.id_categoria > categoria.id_categoria
Ref: vendedor_do_produto.id_vendedor > vendedores.id_vendedor
Ref: vendedor_do_produto.id_produto > produtos.id_produto
Ref: pedidos.id_cliente > clientes.id_cliente
Ref: item_pedido.id_pedido > pedidos.id_pedido
Ref: item_pedido.id_produto > produtos.id_produto
Ref: avaliacao.id_cliente > clientes.id_cliente
Ref: avaliacao.id_produto > produtos.id_produto
Ref: avaliacao.id_pedido > pedidos.id_pedido

Ref: "pedidos"."id_cliente" < "avaliacoes"."id_cliente"

Ref: "pedidos"."id_pedido" < "avaliacoes"."id_pedido"
