CREATE TYPE "tipo_contato" AS ENUM (
  'CELULAR',
  'EMAIL',
  'WHATSAPP'
);

CREATE TABLE "cliente" (
  "id_cli" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "cpf" varchar(11) NOT NULL,
  "nome" varchar(50) NOT NULL
);

CREATE TABLE "contato" (
  "id_contato" int PRIMARY KEY NOT NULL,
  "cliente_id" int NOT NULL,
  "tipo" tipo_contato NOT NULL,
  "informacao" varchar(50) NOT NULL
);

CREATE TABLE "cor" (
  "id_cor" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "desc" varchar(50) NOT NULL,
  "fundo" boolean NOT NULL,
  "letra" boolean NOT NULL
);

CREATE TABLE "material" (
  "id_material" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "descricao_mat" varchar(50) NOT NULL,
  "custo_cm2" decimal(10,2) NOT NULL,
  "valor_letra" decimal NOT NULL
);

CREATE TABLE "desconto" (
  "id_descont" int PRIMARY KEY NOT NULL,
  "percentual" decimal NOT NULL,
  "valor_minimo" decimal NOT NULL,
  "valor_maximo" decimal NOT NULL
);

CREATE TABLE "placa" (
  "placa_id" integer PRIMARY KEY NOT NULL,
  "altura" decimal NOT NULL,
  "largura" decimal NOT NULL,
  "material_id" integer NOT NULL
);

CREATE TABLE "encomenda" (
  "id_encomenda" integer PRIMARY KEY NOT NULL,
  "data" date NOT NULL,
  "entrega" date NOT NULL,
  "desconto_id" decimal NOT NULL,
  "cliente_id" integer NOT NULL
);

CREATE TABLE "item" (
  "id" integer NOT NULL,
  "encomenda_id" integer NOT NULL,
  "placa_cod" integer NOT NULL,
  "quantidade" integer NOT NULL,
  "frase" varchar(30) NOT NULL,
  "cor_fundo_id" integer NOT NULL,
  "cor_letra_id" integer NOT NULL
);

CREATE UNIQUE INDEX "uk_cpf" ON "cliente" ("cpf");

CREATE UNIQUE INDEX "uk_contato" ON "contato" ("cliente_id", "tipo");

ALTER TABLE "encomenda" ADD CONSTRAINT "fk_encomenda_cliente" FOREIGN KEY ("cliente_id") REFERENCES "cliente" ("id_cli") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contato" ADD CONSTRAINT "fk_contato_cliente" FOREIGN KEY ("id_contato") REFERENCES "cliente" ("id_cli") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "item" ADD CONSTRAINT "fk_item_placa" FOREIGN KEY ("placa_cod") REFERENCES "placa" ("placa_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "placa" ADD CONSTRAINT "fk_placa_material" FOREIGN KEY ("material_id") REFERENCES "material" ("id_material") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "item" ADD CONSTRAINT "fk_item_cor_letra" FOREIGN KEY ("cor_letra_id") REFERENCES "cor" ("id_cor") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "item" ADD CONSTRAINT "fk_item_cor_fundo" FOREIGN KEY ("cor_fundo_id") REFERENCES "cor" ("id_cor") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "encomenda" ADD CONSTRAINT "fk_desconto_encomenda" FOREIGN KEY ("desconto_id") REFERENCES "desconto" ("id_descont") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "item" ADD CONSTRAINT "fk_item_encomenda" FOREIGN KEY ("encomenda_id") REFERENCES "encomenda" ("id_encomenda") DEFERRABLE INITIALLY IMMEDIATE;
