CREATE TYPE "contatos" AS ENUM (
  'CELULAR',
  'EMAIL',
  'WHASTAPP'
);

CREATE TABLE "cliente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nome" varchar(50) NOT NULL,
  "saldo" decimal(10,2) NOT NULL DEFAULT 0
);

CREATE TABLE "contato" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "tipo_contato" contatos NOT NULL,
  "cliente_id" integer NOT NULL,
  "informacao" varchar(50) NOT NULL
);

CREATE TABLE "carro" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "placa" char(7) NOT NULL,
  "modelo" varchar(20)
);

CREATE TABLE "cliente_carro" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "cliente_id" integer NOT NULL,
  "carro_id" integer NOT NULL,
  "ativo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "tipo" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "descricao" varchar(20) NOT NULL,
  "valor" decimal(10,2)
);

CREATE TABLE "vaga" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "numero" char(3) NOT NULL,
  "tipo_id" integer NOT NULL
);

CREATE TABLE "estacionamento" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "cliente_carro_id" integer NOT NULL,
  "vaga_id" integer NOT NULL,
  "entrada" timestamp NOT NULL,
  "saida" timestamp
);

CREATE UNIQUE INDEX "uk_cliente_tipo" ON "contato" ("tipo_contato", "cliente_id");

CREATE UNIQUE INDEX "uk_placa" ON "carro" ("placa");

CREATE UNIQUE INDEX "uk_cliente_carro" ON "cliente_carro" ("cliente_id", "carro_id");

CREATE UNIQUE INDEX "uk_vaga_numero" ON "vaga" ("numero");

CREATE UNIQUE INDEX "uk_estacionamento" ON "estacionamento" ("cliente_carro_id", "vaga_id", "entrada");

ALTER TABLE "contato" ADD CONSTRAINT "fk_contato_cliente" FOREIGN KEY ("cliente_id") REFERENCES "cliente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cliente_carro" ADD CONSTRAINT "fk_cliente_carro_cliente" FOREIGN KEY ("cliente_id") REFERENCES "cliente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cliente_carro" ADD CONSTRAINT "fk_cliente_carro_carro" FOREIGN KEY ("carro_id") REFERENCES "carro" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "estacionamento" ADD CONSTRAINT "fk_estacionamento_carro_cliente" FOREIGN KEY ("cliente_carro_id") REFERENCES "cliente_carro" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vaga" ADD CONSTRAINT "fk_vaga_tipo" FOREIGN KEY ("tipo_id") REFERENCES "tipo" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "estacionamento" ADD CONSTRAINT "fk_estacionamento_vaga" FOREIGN KEY ("vaga_id") REFERENCES "vaga" ("id") DEFERRABLE INITIALLY IMMEDIATE;

----------------------------------------------------------------------------------------

Enum "contatos" {
  "CELULAR"
  "EMAIL"
  "WHASTAPP"
}

Table "cliente" {
  "id" INTEGER [pk, not null, increment]
  "nome" varchar(50) [not null]
  "saldo" decimal(10,2) [not null, default: 0]
}

Table "contato" {
  "id" INTEGER [pk, not null, increment]
  "tipo_contato" contatos [not null]
  "cliente_id" integer [not null]
  "informacao" varchar(50) [not null]

  Indexes {
    (tipo_contato, cliente_id) [unique, name: "uk_cliente_tipo"]
  }
}

Table "carro" {
  "id" INTEGER [pk, not null, increment]
  "placa" char(7) [not null]
  "modelo" varchar(20)

  Indexes {
    placa [unique, name: "uk_placa"]
  }
}

Table "cliente_carro" {
  "id" INTEGER [pk, not null, increment]
  "cliente_id" integer [not null]
  "carro_id" integer [not null]
  "ativo" boolean [not null, default: true]

  Indexes {
    (cliente_id, carro_id) [unique, name: "uk_cliente_carro"]
  }
}

Table "tipo" {
  "id" INTEGER [pk, not null, increment]
  "descricao" varchar(20) [not null]
  "valor" decimal(10,2)
}

Table "vaga" {
  "id" INTEGER [pk, not null, increment]
  "numero" char(3) [not null]
  "tipo_id" integer [not null]

  Indexes {
    numero [unique, name: "uk_vaga_numero"]
  }
}

Table "estacionamento" {
  "id" INTEGER [pk, not null, increment]
  "cliente_carro_id" integer [not null]
  "vaga_id" integer [not null]
  "entrada" timestamp [not null]
  "saida" timestamp

  Indexes {
    (cliente_carro_id, vaga_id, entrada) [unique, name: "uk_estacionamento"]
  }
}

Ref "fk_contato_cliente":"cliente"."id" < "contato"."cliente_id"

Ref "fk_cliente_carro_cliente":"cliente"."id" < "cliente_carro"."cliente_id"

Ref "fk_cliente_carro_carro":"carro"."id" < "cliente_carro"."carro_id"

Ref "fk_estacionamento_carro_cliente":"cliente_carro"."id" < "estacionamento"."cliente_carro_id"

Ref "fk_vaga_tipo":"tipo"."id" < "vaga"."tipo_id"

Ref "fk_estacionamento_vaga":"vaga"."id" < "estacionamento"."vaga_id"
