CREATE TYPE "tipo_contato" AS ENUM (
  'WHATSAPP',
  'EMAIL',
  'TELEFONE'
);

CREATE TABLE "cliente" (
  "id_cli" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "cpf" char(11) NOT NULL,
  "nome" varchar(50) NOT NULL,
  "saldo" decimal(10,2) NOT NULL DEFAULT 0
);

CREATE TABLE "carro" (
  "id_carro" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "car_placa" char(7) NOT NULL,
  "modelo" varchar(50) NOT NULL
);

CREATE TABLE "contato" (
  "id_contato" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "cli_id" int NOT NULL,
  "ctt_tipo" tipo_contato NOT NULL,
  "informacao" varchar(50) NOT NULL
);

CREATE TABLE "tipo" (
  "id_tipo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "descricao" varchar(20) NOT NULL,
  "valor" decimal(10,2) NOT NULL
);

CREATE TABLE "vaga" (
  "id_vaga" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "vag_numero" char(5) NOT NULL,
  "tip_id" int NOT NULL
);

CREATE TABLE "proprietario" (
  "id_proprietario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "cli_id" int NOT NULL,
  "carro_id" int NOT NULL,
  "ativo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "estacionamento" (
  "id_estacionamento" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "carro_id" int NOT NULL,
  "vaga_id" int NOT NULL,
  "entrada" timestamp NOT NULL,
  "saida" timestamp
);

-- unique indexes
CREATE UNIQUE INDEX "uk_cpf" ON "cliente" ("cpf");
CREATE UNIQUE INDEX "uk_placa" ON "carro" ("car_placa");
CREATE UNIQUE INDEX "uk_vaga_numero" ON "vaga" ("vag_numero");
CREATE UNIQUE INDEX "uk_contato" ON "contato" ("cli_id", "ctt_tipo");
CREATE UNIQUE INDEX "uk_proprietario" ON "proprietario" ("cli_id", "carro_id");

-- foreign keys
ALTER TABLE "contato" ADD CONSTRAINT "fk_contato_cliente"
  FOREIGN KEY ("cli_id") REFERENCES "cliente" ("id_cli") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vaga" ADD CONSTRAINT "fk_vaga_tipo"
  FOREIGN KEY ("tip_id") REFERENCES "tipo" ("id_tipo") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "proprietario" ADD CONSTRAINT "fk_proprietario_cliente"
  FOREIGN KEY ("cli_id") REFERENCES "cliente" ("id_cli") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "proprietario" ADD CONSTRAINT "fk_proprietario_carro"
  FOREIGN KEY ("carro_id") REFERENCES "carro" ("id_carro") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "estacionamento" ADD CONSTRAINT "fk_estacionamento_carro"
  FOREIGN KEY ("carro_id") REFERENCES "carro" ("id_carro") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "estacionamento" ADD CONSTRAINT "fk_estacionamento_vaga"
  FOREIGN KEY ("vaga_id") REFERENCES "vaga" ("id_vaga") DEFERRABLE INITIALLY IMMEDIATE;

----------------------------------------------------------------------------------------

Enum "contatos" {
  "CELULAR"
  "EMAIL"
  "WHASTAPP"
}

Table "cliente" {
  "id" INTEGER [pk, not null, increment]
  "nome" varchar(50) [not null]
  "saldo" decimal(10,2) [not null, default: 0]
}

Table "contato" {
  "id" INTEGER [pk, not null, increment]
  "tipo_contato" contatos [not null]
  "cliente_id" integer [not null]
  "informacao" varchar(50) [not null]

  Indexes {
    (tipo_contato, cliente_id) [unique, name: "uk_cliente_tipo"]
  }
}

Table "carro" {
  "id" INTEGER [pk, not null, increment]
  "placa" char(7) [not null]
  "modelo" varchar(20)

  Indexes {
    placa [unique, name: "uk_placa"]
  }
}

Table "cliente_carro" {
  "id" INTEGER [pk, not null, increment]
  "cliente_id" integer [not null]
  "carro_id" integer [not null]
  "ativo" boolean [not null, default: true]

  Indexes {
    (cliente_id, carro_id) [unique, name: "uk_cliente_carro"]
  }
}

Table "tipo" {
  "id" INTEGER [pk, not null, increment]
  "descricao" varchar(20) [not null]
  "valor" decimal(10,2)
}

Table "vaga" {
  "id" INTEGER [pk, not null, increment]
  "numero" char(3) [not null]
  "tipo_id" integer [not null]

  Indexes {
    numero [unique, name: "uk_vaga_numero"]
  }
}

Table "estacionamento" {
  "id" INTEGER [pk, not null, increment]
  "cliente_carro_id" integer [not null]
  "vaga_id" integer [not null]
  "entrada" timestamp [not null]
  "saida" timestamp

  Indexes {
    (cliente_carro_id, vaga_id, entrada) [unique, name: "uk_estacionamento"]
  }
}

Ref "fk_contato_cliente":"cliente"."id" < "contato"."cliente_id"

Ref "fk_cliente_carro_cliente":"cliente"."id" < "cliente_carro"."cliente_id"

Ref "fk_cliente_carro_carro":"carro"."id" < "cliente_carro"."carro_id"

Ref "fk_estacionamento_carro_cliente":"cliente_carro"."id" < "estacionamento"."cliente_carro_id"

Ref "fk_vaga_tipo":"tipo"."id" < "vaga"."tipo_id"

Ref "fk_estacionamento_vaga":"vaga"."id" < "estacionamento"."vaga_id"
